# Generated by Django 5.0 on 2024-07-17 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=20)),
                ('link', models.URLField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio_app.about')),
            ],
        ),
    ]
