# Generated by Django 5.0.7 on 2024-07-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio_app', '0002_porfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porfile',
            name='link',
            field=models.URLField(max_length=20),
        ),
    ]
