# Generated by Django 5.0.7 on 2024-07-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio_app', '0003_alter_porfile_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
