# Generated by Django 5.0.7 on 2024-07-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio_app', '0004_home_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
